name: new_friends_date_app
description: A new Flutter project.

publish_to: 'none' 
version: 2.0.3+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_foreground_task: ^6.0.0+1
  flutter_windowmanager: ^0.2.0
  awesome_notifications: ^0.7.4+1
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  agora_rtc_engine: ^6.2.1
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  google_fonts: ^5.1.0
  flutter_bounce: ^1.1.0
  auto_size_text: ^3.0.0
  permission_handler: ^10.4.3
  dots_indicator: ^3.0.0
  image_picker: ^1.0.1
  dio: ^5.3.0
  hive: ^2.2.3
  flutter_advanced_drawer: ^1.3.5
  in_app_review: ^2.0.6
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  curved_nav_bar: ^0.0.2
  animated_bottom_navigation_bar: ^1.2.0
  wakelock: ^0.6.2
  just_audio: ^0.9.34
  cached_network_image: ^3.2.3
  firebase_storage: ^11.2.5
  emoji_picker_flutter: ^1.6.1
  background_fetch: ^1.2.0
  image_gallery_saver: ^2.0.3
  flutter_background: ^1.2.0
  flutter_foreground_service: ^0.4.1
  razorpay_flutter: ^1.3.0
  dropdown_button2: ^2.3.8
  flutter_callkit_incoming: ^2.0.0+1
  easy_image_viewer: ^1.2.1
  youtube_player_flutter: ^8.1.2
  liquid_pull_to_refresh: ^3.0.1
  linkfy_text: ^1.1.5
  readmore: ^2.2.0
  any_link_preview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/ringtone/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 